"""initial schema

Revision ID: a61e2bb7d2a3
Revises: 
Create Date: 2026-08-29 07:22:19.519387
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a61e2bb7d2a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provinces_slug'), ['slug'], unique=True)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='syncstatus', native_enum=False, length=16), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_amended', sa.Integer(), nullable=False),
    sa.Column('records_expired', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('notifications_sent', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index('ix_sync_runs_started', ['started_at'], unique=False)

    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('ocid', sa.String(length=255), nullable=True),
    sa.Column('tender_number', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organisation', sa.String(length=512), nullable=True),
    sa.Column('organisation_identifier', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('municipality', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tender_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'CANCELLED', 'AMENDED', 'EXPIRED', name='tenderstatus', native_enum=False, length=16), nullable=False),
    sa.Column('advertised_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('closing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_method', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_tender_source_external')
    )
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.create_index('ix_tenders_advertised_date', ['advertised_date'], unique=False)
        batch_op.create_index('ix_tenders_category', ['category'], unique=False)
        batch_op.create_index('ix_tenders_closing_at', ['closing_at'], unique=False)
        batch_op.create_index('ix_tenders_first_seen_at', ['first_seen_at'], unique=False)
        batch_op.create_index('ix_tenders_organisation', ['organisation'], unique=False)
        batch_op.create_index('ix_tenders_province', ['province'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenders_source'), ['source'], unique=False)
        batch_op.create_index('ix_tenders_source_ocid', ['source', 'ocid'], unique=False)
        batch_op.create_index('ix_tenders_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_client_id'), ['client_id'], unique=True)

    op.create_table('notification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('NEW_TENDER', 'TENDER_AMENDED', 'DEADLINE_REMINDER', name='notificationtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='notificationeventstatus', native_enum=False, length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tender_id', 'notification_type', name='uq_notification_dedup')
    )
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.create_index('ix_notif_events_tender', ['tender_id'], unique=False)
        batch_op.create_index('ix_notif_events_user', ['user_id'], unique=False)

    op.create_table('notification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    with op.batch_alter_table('notification_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_tokens_user', ['user_id'], unique=False)

    op.create_table('saved_tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tender_id', name='uq_saved_tender')
    )
    op.create_table('tender_amendments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tender_amendments', schema=None) as batch_op:
        batch_op.create_index('ix_amendments_tender', ['tender_id'], unique=False)

    op.create_table('tender_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'category_id', name='uq_tender_category')
    )
    with op.batch_alter_table('tender_categories', schema=None) as batch_op:
        batch_op.create_index('ix_tender_categories_category', ['category_id'], unique=False)

    op.create_table('tender_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'url', name='uq_document_tender_url')
    )
    with op.batch_alter_table('tender_documents', schema=None) as batch_op:
        batch_op.create_index('ix_documents_tender', ['tender_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('province_id', sa.Integer(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'province_id', name='uq_user_pref')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index('ix_user_pref_category', ['category_id'], unique=False)
        batch_op.create_index('ix_user_pref_province', ['province_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index('ix_user_pref_province')
        batch_op.drop_index('ix_user_pref_category')

    op.drop_table('user_preferences')
    with op.batch_alter_table('tender_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_tender')

    op.drop_table('tender_documents')
    with op.batch_alter_table('tender_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_tender_categories_category')

    op.drop_table('tender_categories')
    with op.batch_alter_table('tender_amendments', schema=None) as batch_op:
        batch_op.drop_index('ix_amendments_tender')

    op.drop_table('tender_amendments')
    op.drop_table('saved_tenders')
    with op.batch_alter_table('notification_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_tokens_user')

    op.drop_table('notification_tokens')
    with op.batch_alter_table('notification_events', schema=None) as batch_op:
        batch_op.drop_index('ix_notif_events_user')
        batch_op.drop_index('ix_notif_events_tender')

    op.drop_table('notification_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_client_id'))

    op.drop_table('users')
    with op.batch_alter_table('tenders', schema=None) as batch_op:
        batch_op.drop_index('ix_tenders_status')
        batch_op.drop_index('ix_tenders_source_ocid')
        batch_op.drop_index(batch_op.f('ix_tenders_source'))
        batch_op.drop_index('ix_tenders_province')
        batch_op.drop_index('ix_tenders_organisation')
        batch_op.drop_index('ix_tenders_first_seen_at')
        batch_op.drop_index('ix_tenders_closing_at')
        batch_op.drop_index('ix_tenders_category')
        batch_op.drop_index('ix_tenders_advertised_date')

    op.drop_table('tenders')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_runs_started')

    op.drop_table('sync_runs')
    with op.batch_alter_table('provinces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provinces_slug'))

    op.drop_table('provinces')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))

    op.drop_table('categories')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    # ### end Alembic commands ###
